### ISSUE TITLE
Redo entire project using Godot Engine

### ISSUE THREAD

**Issue by ljleb** [XavierCL/UnitWorld-solo#11]
@John-WilliamLebel recently suggested using [Godot](https://godotengine.org/) to create the game instead of C++. I though about reporting this idea in the issue tracker.

## Disadvantages of using Godot over C++:

- ### we will have to implement features that are already completed:
  - #### graphical animations
  - #### simple client-server connection

## Advantages of using Godot over C++:

- ### some features are already efficiently implemented:
  - #### graphical animations
  - #### [user inputs](https://docs.godotengine.org/en/3.1/tutorials/inputs/inputevent.html)

- ### some features are simpler to efficiently implement:
  - #### [physics](https://docs.godotengine.org/en/3.1/tutorials/physics/physics_introduction.html) ([collisions](https://docs.godotengine.org/en/2.1/learning/features/physics/physics_introduction.html#physics-global-variables), map boundaries, unit movement...)
  - #### [client-server communication](https://docs.godotengine.org/en/3.1/tutorials/networking/high_level_multiplayer.html#rpc)

**Comment by XavierCL** [comment]
Won't do, you might please yourself though.
